ALTER TABLE "tenants"
  ADD COLUMN "public_display_name" TEXT,
  ADD COLUMN "logo_url" TEXT,
  ADD COLUMN "logo_file_key" TEXT,
  ADD COLUMN "postal_code" TEXT,
  ADD COLUMN "neighborhood" TEXT,
  ADD COLUMN "address_complement" TEXT,
  ADD COLUMN "google_maps_url" TEXT,
  ADD COLUMN "service_location" TEXT NOT NULL DEFAULT 'BUSINESS_ADDRESS',
  ADD COLUMN "timezone" TEXT NOT NULL DEFAULT 'America/Sao_Paulo',
  ADD COLUMN "locale" TEXT NOT NULL DEFAULT 'pt-BR',
  ADD COLUMN "currency" TEXT NOT NULL DEFAULT 'BRL',
  ADD COLUMN "week_starts_on" INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN "time_format" TEXT NOT NULL DEFAULT '24H',
  ADD COLUMN "default_appointment_duration" INTEGER NOT NULL DEFAULT 30,
  ADD COLUMN "default_slot_interval" INTEGER NOT NULL DEFAULT 30,
  ADD COLUMN "min_booking_notice_minutes" INTEGER NOT NULL DEFAULT 120,
  ADD COLUMN "max_booking_advance_days" INTEGER NOT NULL DEFAULT 30,
  ADD COLUMN "allow_customer_cancellation" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN "allow_customer_rescheduling" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN "cancellation_notice_hours" INTEGER NOT NULL DEFAULT 24,
  ADD COLUMN "confirmation_message_template" TEXT NOT NULL DEFAULT 'Olá, {cliente}! Seu agendamento de {serviço} foi confirmado para {data} às {hora}.',
  ADD COLUMN "reminder_message_template" TEXT NOT NULL DEFAULT 'Olá, {cliente}! Passando para lembrar do seu agendamento de {serviço} em {data} às {hora}.',
  ADD COLUMN "cancellation_message_template" TEXT NOT NULL DEFAULT 'Olá, {cliente}. Seu agendamento de {serviço} em {data} às {hora} foi cancelado.',
  ADD COLUMN "enable_automatic_reminders" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "reminder_lead_hours" INTEGER NOT NULL DEFAULT 24;
